# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://PendragonGame.github.io
title: Pendragon
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  A 2d RPG game, named Pendragon
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Windows
    url: https://twitter.com/SBootstrap
  - title: Mac
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: Linux
    url: 
