# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://PendragonGame.github.io
title: Pendragon
email: https://github.com/PendragonGame/pendragon
author: Your Name
description: > # "Write an awesome description for your new site here. 
  A 2d RPG game, named Pendragon
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: windows
    url: https://github.com/PendragonGame/pendragon/releases/download/v1.0.0/Pendragon.1.0.0.exe
  - title: apple
    url: https://github.com/PendragonGame/pendragon/releases/download/v1.0.0/Pendragon-1.0.0-mac.zip
  - title: linux
    url: https://github.com/PendragonGame/pendragon/releases/download/v0.3.0/Pendragon-Linux-x86_64.zip
